version: "3"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "${POSTGRES_PORT:-5433}:5432"
    networks:
      - postgres
      - backend
    restart: unless-stopped

  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
  #   volumes:
  #     - pgadmin:/root/.pgadmin
  #   ports:
  #     - "${PGADMIN_PORT:-5050}:80"
  #   networks:
  #     - postgres
  #   restart: unless-stopped

  fastapi:
    env_file:
      - .env
    depends_on:
      - postgres
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_SERVER: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "8000:8000"
    volumes:
      - ./app:/src/app
    command: uvicorn app.main:app --host 0.0.0.0 --reload
    networks:
      - backend
    stdin_open: true # Add this line into your service
    tty: true

networks:
  postgres:
    driver: bridge
  backend:
    driver: bridge

volumes:
  postgres:
  # pgadmin:
