"""Adding extra columns for asset_mint_tx

Revision ID: 223163d5fe81
Revises: 362880fc56c6
Create Date: 2022-08-03 06:04:27.195050

"""
from __future__ import annotations

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = '223163d5fe81'
down_revision = '362880fc56c6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_mint_tx', sa.Column('quantity', sa.Integer(), nullable=True))
    op.add_column('asset_mint_tx', sa.Column('tx_hash', sa.String(), nullable=True))
    op.add_column('asset_mint_tx', sa.Column('tx_time', sa.DateTime(), nullable=True))
    op.add_column('asset_mint_tx', sa.Column('image', sa.String(), nullable=True))
    op.add_column(
        'asset_mint_tx', sa.Column(
            'metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True,
        ),
    )
    op.add_column(
        'asset_mint_tx', sa.Column(
            'files', postgresql.JSONB(astext_type=sa.Text()), nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset_mint_tx', 'files')
    op.drop_column('asset_mint_tx', 'metadata')
    op.drop_column('asset_mint_tx', 'image')
    op.drop_column('asset_mint_tx', 'tx_time')
    op.drop_column('asset_mint_tx', 'tx_hash')
    op.drop_column('asset_mint_tx', 'quantity')
    # ### end Alembic commands ###
