"""Adding FK for asset tables

Revision ID: 362880fc56c6
Revises: 8a5e8dc384b4
Create Date: 2022-07-29 14:50:39.696257

"""
from __future__ import annotations

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = '362880fc56c6'
down_revision = '8a5e8dc384b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset', sa.Column('latest_mint_tx_id', sa.Integer(), nullable=True))
    op.add_column('asset', sa.Column('latest_tx_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f('fk_asset_latest_mint_tx_id_asset_mint_tx'),
        'asset', 'asset_mint_tx', ['latest_mint_tx_id'], ['id'],
    )
    op.create_foreign_key(
        op.f('fk_asset_latest_tx_id_asset_tx'),
        'asset', 'asset_tx', ['latest_tx_id'], ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f('fk_asset_latest_tx_id_asset_tx'),
        'asset', type_='foreignkey',
    )
    op.drop_constraint(
        op.f('fk_asset_latest_mint_tx_id_asset_mint_tx'),
        'asset', type_='foreignkey',
    )
    op.drop_column('asset', 'latest_tx_id')
    op.drop_column('asset', 'latest_mint_tx_id')
    # ### end Alembic commands ###
