"""Adding Foreign Keys for Social Connection

Revision ID: 49d27e1a9427
Revises: ee8c4b5de42f
Create Date: 2022-08-23 01:37:54.666710

"""
from __future__ import annotations

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = '49d27e1a9427'
down_revision = 'ee8c4b5de42f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connection', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f('fk_connection_user_id_user'),
        'connection', 'user', ['user_id'], ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f('fk_connection_user_id_user'),
        'connection', type_='foreignkey',
    )
    op.drop_column('connection', 'user_id')
    # ### end Alembic commands ###
