"""adding index

Revision ID: 5f22f981bf85
Revises: c811eb716ba3
Create Date: 2022-09-08 02:42:04.533915

"""
from __future__ import annotations

from alembic import op


# revision identifiers, used by Alembic.
revision = '5f22f981bf85'
down_revision = 'c811eb716ba3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_wallet_address', 'wallet', ['address'], unique=False)
    op.create_index(
        'ix_collection_policy_id', 'collection',
        ['policy_id'], unique=False,
    )
    op.create_index('ix_asset_ext_asset_id', 'asset_ext', ['asset_id'], unique=False)
    op.create_index('ix_asset_fingerprint', 'asset', ['fingerprint'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_asset_fingerprint', table_name='asset')
    op.drop_index('ix_asset_ext_asset_id', table_name='asset_ext')
    op.drop_index('ix_collection_policy_id', table_name='collection')
    op.drop_index('ix_wallet_address', table_name='wallet')
    # ### end Alembic commands ###
