"""Re adding Quantity Column with Arbritrary Precision

Revision ID: 63f937d0b958
Revises: a7fcb0d48681
Create Date: 2022-08-03 07:53:03.339780

"""
from __future__ import annotations

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = '63f937d0b958'
down_revision = 'a7fcb0d48681'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'asset_mint_tx', sa.Column(
            'quantity', sa.Numeric(precision=20, scale=0), nullable=True,
        ),
    )
    op.add_column(
        'asset_tx', sa.Column(
            'quantity', sa.Numeric(precision=20, scale=0), nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset_tx', 'quantity')
    op.drop_column('asset_mint_tx', 'quantity')
    # ### end Alembic commands ###
