"""Adding Foreign Keys

Revision ID: 674676ee9836
Revises: 82eb781e7e85
Create Date: 2022-07-26 05:28:19.172015

"""
from __future__ import annotations

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = '674676ee9836'
down_revision = '82eb781e7e85'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'gallery_asset',
        sa.Column('gallery_id', sa.Integer(), nullable=False),
        sa.Column('asset_id', sa.Integer(), nullable=False),
        sa.Column('datetime_created', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ['asset_id'], ['asset.id'],
            name=op.f('fk_gallery_asset_asset_id_asset'),
        ),
        sa.ForeignKeyConstraint(
            ['gallery_id'], ['gallery.id'],
            name=op.f('fk_gallery_asset_gallery_id_gallery'),
        ),
        sa.PrimaryKeyConstraint(
            'gallery_id', 'asset_id',
            name=op.f('pk_gallery_asset'),
        ),
    )
    op.add_column('asset', sa.Column('collection_id', sa.Integer(), nullable=True))
    op.add_column('asset', sa.Column('current_owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f('fk_asset_current_owner_id_owner'),
        'asset', 'owner', ['current_owner_id'], ['id'],
    )
    op.create_foreign_key(
        op.f('fk_asset_collection_id_collection'),
        'asset', 'collection', ['collection_id'], ['id'],
    )
    op.add_column('gallery', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f('fk_gallery_user_id_user'),
        'gallery', 'user', ['user_id'], ['id'],
    )
    op.add_column('owner', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f('fk_owner_user_id_user'),
        'owner', 'user', ['user_id'], ['id'],
    )
    op.add_column('user', sa.Column('pfp_asset_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f('fk_user_pfp_asset_id_asset'),
        'user', 'asset', ['pfp_asset_id'], ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_user_pfp_asset_id_asset'), 'user', type_='foreignkey')
    op.drop_column('user', 'pfp_asset_id')
    op.drop_constraint(op.f('fk_owner_user_id_user'), 'owner', type_='foreignkey')
    op.drop_column('owner', 'user_id')
    op.drop_constraint(op.f('fk_gallery_user_id_user'), 'gallery', type_='foreignkey')
    op.drop_column('gallery', 'user_id')
    op.drop_constraint(
        op.f('fk_asset_collection_id_collection'),
        'asset', type_='foreignkey',
    )
    op.drop_constraint(
        op.f('fk_asset_current_owner_id_owner'),
        'asset', type_='foreignkey',
    )
    op.drop_column('asset', 'current_owner_id')
    op.drop_column('asset', 'collection_id')
    op.drop_table('gallery_asset')
    # ### end Alembic commands ###
