"""Drop Quantity field

Revision ID: a7fcb0d48681
Revises: 223163d5fe81
Create Date: 2022-08-03 07:51:21.683447

"""
from __future__ import annotations

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = 'a7fcb0d48681'
down_revision = '223163d5fe81'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset_mint_tx', 'quantity')
    op.drop_column('asset_tx', 'quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'asset_tx', sa.Column(
            'quantity', sa.INTEGER(), autoincrement=False, nullable=True,
        ),
    )
    op.add_column(
        'asset_mint_tx', sa.Column(
            'quantity', sa.INTEGER(), autoincrement=False, nullable=True,
        ),
    )
    # ### end Alembic commands ###
