"""Set social connection user.id nullable to False

Revision ID: c811eb716ba3
Revises: 49d27e1a9427
Create Date: 2022-08-23 01:43:29.448263

"""
from __future__ import annotations

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = 'c811eb716ba3'
down_revision = '49d27e1a9427'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'connection', 'user_id',
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'connection', 'user_id',
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    # ### end Alembic commands ###
