"""Init

Revision ID: d5ed26486b2e
Revises:
Create Date: 2022-07-25 03:29:58.419760

"""
from __future__ import annotations

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = 'd5ed26486b2e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'asset',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('collection_id', sa.Integer(), nullable=True),
        sa.Column('hash', sa.String(), nullable=True),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('fingerprint', sa.String(), nullable=True),
        sa.Column('current_owner_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['collection_id'], ['collection.id']),
        sa.ForeignKeyConstraint(['current_owner_id'], ['owner.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_asset_id'), 'asset', ['id'], unique=False)
    op.create_table(
        'collection',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('policy_id', sa.String(), nullable=False),
        sa.Column('title', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_collection_id'), 'collection', ['id'], unique=False)
    op.create_table(
        'connection',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('connection_id', sa.String(), nullable=True),
        sa.Column(
            'connection_type', sa.Enum(
                'DISCORD', 'TWITTER', name='connectiontype',
            ), nullable=True,
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_connection_id'), 'connection', ['id'], unique=False)
    op.create_table(
        'owner',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('address', sa.String(), nullable=True),
        sa.Column('address_type', sa.String(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_owner_id'), 'owner', ['id'], unique=False)
    op.create_table(
        'user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('pfp_asset_id', sa.Integer(), nullable=True),
        sa.Column('alias', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['pfp_asset_id'], ['asset.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table(
        'gallery',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('title', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_gallery_id'), 'gallery', ['id'], unique=False)
    op.create_table(
        'gallery_asset',
        sa.Column('gallery_id', sa.Integer(), nullable=False),
        sa.Column('asset_id', sa.Integer(), nullable=False),
        sa.Column('datetime_created', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['asset_id'], ['asset.id']),
        sa.ForeignKeyConstraint(['gallery_id'], ['gallery.id']),
        sa.PrimaryKeyConstraint('gallery_id', 'asset_id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gallery_asset')
    op.drop_index(op.f('ix_gallery_id'), table_name='gallery')
    op.drop_table('gallery')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_owner_id'), table_name='owner')
    op.drop_table('owner')
    op.drop_index(op.f('ix_connection_id'), table_name='connection')
    op.drop_table('connection')
    op.drop_index(op.f('ix_collection_id'), table_name='collection')
    op.drop_table('collection')
    op.drop_index(op.f('ix_asset_id'), table_name='asset')
    op.drop_table('asset')
    # ### end Alembic commands ###
