"""Adding Foreign Keys

Revision ID: ee8c4b5de42f
Revises: d0e064a71ea6
Create Date: 2022-08-13 03:18:27.245822

"""
from __future__ import annotations

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = 'ee8c4b5de42f'
down_revision = 'd0e064a71ea6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'gallery_asset',
        sa.Column('gallery_id', sa.Integer(), nullable=False),
        sa.Column('asset_id', sa.Integer(), nullable=False),
        sa.Column('datetime_created', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ['asset_id'], ['asset.id'],
            name=op.f('fk_gallery_asset_asset_id_asset'),
        ),
        sa.ForeignKeyConstraint(
            ['gallery_id'], ['gallery.id'],
            name=op.f('fk_gallery_asset_gallery_id_gallery'),
        ),
        sa.PrimaryKeyConstraint(
            'gallery_id', 'asset_id',
            name=op.f('pk_gallery_asset'),
        ),
    )
    op.add_column('asset', sa.Column('collection_id', sa.Integer(), nullable=True))
    op.add_column('asset', sa.Column('current_wallet_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f('fk_asset_current_wallet_id_wallet'),
        'asset', 'wallet', ['current_wallet_id'], ['id'],
    )
    op.create_foreign_key(
        op.f('fk_asset_collection_id_collection'),
        'asset', 'collection', ['collection_id'], ['id'],
    )
    op.add_column('asset_ext', sa.Column('asset_id', sa.Integer(), nullable=True))
    op.add_column(
        'asset_ext', sa.Column(
            'latest_mint_tx_id', sa.Integer(), nullable=True,
        ),
    )
    op.add_column('asset_ext', sa.Column('latest_tx_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f('fk_asset_ext_latest_tx_id_asset_tx'),
        'asset_ext', 'asset_tx', ['latest_tx_id'], ['id'],
    )
    op.create_foreign_key(
        op.f('fk_asset_ext_latest_mint_tx_id_asset_mint_tx'),
        'asset_ext', 'asset_mint_tx', ['latest_mint_tx_id'], ['id'],
    )
    op.create_foreign_key(
        op.f('fk_asset_ext_asset_id_asset'),
        'asset_ext', 'asset', ['asset_id'], ['id'],
    )
    op.add_column('asset_mint_tx', sa.Column('asset_id', sa.Integer(), nullable=True))
    op.add_column('asset_mint_tx', sa.Column('wallet_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f('fk_asset_mint_tx_wallet_id_wallet'),
        'asset_mint_tx', 'wallet', ['wallet_id'], ['id'],
    )
    op.create_foreign_key(
        op.f('fk_asset_mint_tx_asset_id_asset'),
        'asset_mint_tx', 'asset', ['asset_id'], ['id'],
    )
    op.add_column('asset_tx', sa.Column('asset_id', sa.Integer(), nullable=True))
    op.add_column('asset_tx', sa.Column('wallet_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f('fk_asset_tx_asset_id_asset'),
        'asset_tx', 'asset', ['asset_id'], ['id'],
    )
    op.create_foreign_key(
        op.f('fk_asset_tx_wallet_id_wallet'),
        'asset_tx', 'wallet', ['wallet_id'], ['id'],
    )
    op.add_column('gallery', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f('fk_gallery_user_id_user'),
        'gallery', 'user', ['user_id'], ['id'],
    )
    op.add_column('user', sa.Column('pfp_asset_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f('fk_user_pfp_asset_id_asset'),
        'user', 'asset', ['pfp_asset_id'], ['id'],
    )
    op.add_column('wallet', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f('fk_wallet_user_id_user'),
        'wallet', 'user', ['user_id'], ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_wallet_user_id_user'), 'wallet', type_='foreignkey')
    op.drop_column('wallet', 'user_id')
    op.drop_constraint(op.f('fk_user_pfp_asset_id_asset'), 'user', type_='foreignkey')
    op.drop_column('user', 'pfp_asset_id')
    op.drop_constraint(op.f('fk_gallery_user_id_user'), 'gallery', type_='foreignkey')
    op.drop_column('gallery', 'user_id')
    op.drop_constraint(
        op.f('fk_asset_tx_wallet_id_wallet'),
        'asset_tx', type_='foreignkey',
    )
    op.drop_constraint(
        op.f('fk_asset_tx_asset_id_asset'),
        'asset_tx', type_='foreignkey',
    )
    op.drop_column('asset_tx', 'wallet_id')
    op.drop_column('asset_tx', 'asset_id')
    op.drop_constraint(
        op.f('fk_asset_mint_tx_asset_id_asset'),
        'asset_mint_tx', type_='foreignkey',
    )
    op.drop_constraint(
        op.f('fk_asset_mint_tx_wallet_id_wallet'),
        'asset_mint_tx', type_='foreignkey',
    )
    op.drop_column('asset_mint_tx', 'wallet_id')
    op.drop_column('asset_mint_tx', 'asset_id')
    op.drop_constraint(
        op.f('fk_asset_ext_asset_id_asset'),
        'asset_ext', type_='foreignkey',
    )
    op.drop_constraint(
        op.f('fk_asset_ext_latest_mint_tx_id_asset_mint_tx'),
        'asset_ext', type_='foreignkey',
    )
    op.drop_constraint(
        op.f('fk_asset_ext_latest_tx_id_asset_tx'),
        'asset_ext', type_='foreignkey',
    )
    op.drop_column('asset_ext', 'latest_tx_id')
    op.drop_column('asset_ext', 'latest_mint_tx_id')
    op.drop_column('asset_ext', 'asset_id')
    op.drop_constraint(
        op.f('fk_asset_collection_id_collection'),
        'asset', type_='foreignkey',
    )
    op.drop_constraint(
        op.f('fk_asset_current_wallet_id_wallet'),
        'asset', type_='foreignkey',
    )
    op.drop_column('asset', 'current_wallet_id')
    op.drop_column('asset', 'collection_id')
    op.drop_table('gallery_asset')
    # ### end Alembic commands ###
